//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAONAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAONAM()
        {
            this.BAOCAOTHANGs = new HashSet<BAOCAOTHANG>();
        }
    
        public string MaBCNam { get; set; }
        public Nullable<short> Nam { get; set; }
        public Nullable<double> TongDoanhThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTHANG> BAOCAOTHANGs { get; set; }
    }
}
