//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAOTHANG()
        {
            this.CT_BCTHANG = new HashSet<CT_BCTHANG>();
        }
    
        public string MaBCThang { get; set; }
        public string MaBCNam { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> Nam { get; set; }
        public Nullable<double> TongDoanhThuThang { get; set; }
        public Nullable<short> TongChuyenBay { get; set; }
        public Nullable<double> TiLe { get; set; }
    
        public virtual BAOCAONAM BAOCAONAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BCTHANG> CT_BCTHANG { get; set; }
    }
}
