//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCTHANG
    {
        public string MaBCThang { get; set; }
        public string MaChuyenBay { get; set; }
        public Nullable<short> SoVe { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<double> TiLe { get; set; }
    
        public virtual BAOCAOTHANG BAOCAOTHANG { get; set; }
        public virtual CHUYENBAY CHUYENBAY { get; set; }
    }
}
