//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_CHUYENBAY
    {
        public int MaCTCB { get; set; }
        public string MaChuyenBay { get; set; }
        public string MaSanBayTrungGian { get; set; }
        public Nullable<short> ThoiGianDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
    }
}
