//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightKetDBEntities : DbContext
    {
        public FlightKetDBEntities()
            : base("name=FlightKetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAONAM> BAOCAONAMs { get; set; }
        public virtual DbSet<BAOCAOTHANG> BAOCAOTHANGs { get; set; }
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<CT_BCTHANG> CT_BCTHANG { get; set; }
        public virtual DbSet<CT_CHUYENBAY> CT_CHUYENBAY { get; set; }
        public virtual DbSet<CT_HANGVE> CT_HANGVE { get; set; }
        public virtual DbSet<HANGVE> HANGVEs { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACHes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUDATCHO> PHIEUDATCHOes { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<VECHUYENBAY> VECHUYENBAYs { get; set; }
    }
}
