//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATCHO
    {
        public int MaPhieuDatCho { get; set; }
        public string MaChuyenBay { get; set; }
        public string MaHanhKhach { get; set; }
        public string MaHangVe { get; set; }
        public Nullable<double> GiaTien { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual HANGVE HANGVE { get; set; }
        public virtual HANHKHACH HANHKHACH { get; set; }
    }
}
