//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLE()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> CanNhapLichChuyenBay { get; set; }
        public Nullable<bool> CanBanVe { get; set; }
        public Nullable<bool> CanGhiNhanDatVe { get; set; }
        public Nullable<bool> CanTraCuuChuyenBay { get; set; }
        public Nullable<bool> CanLapBaoCao { get; set; }
        public Nullable<bool> CanThayDoiQuyDinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
