//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightket
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public short ID { get; set; }
        public Nullable<short> ThoiGianBayToiThieu { get; set; }
        public Nullable<short> SoSanBayTrungGianToiDa { get; set; }
        public Nullable<short> ThoiGianDungToiThieu { get; set; }
        public Nullable<short> ThoiGianDungToiDa { get; set; }
        public Nullable<short> SoGioDatVeTruocKhoiHanh { get; set; }
        public Nullable<short> SoGioHuyPhieuTruocKhoiHanh { get; set; }
    }
}
